@startuml

title __CHATWINDOW's Class Diagram__\n

  namespace com.client.chatwindow {
    class com.client.chatwindow.CellRenderer {
        + call()
    }
  }
  

  namespace com.client.chatwindow {
    class com.client.chatwindow.ChatController {
        + messageBox : TextArea
        ~ borderPane : BorderPane
        ~ chatPane : ListView
        ~ closeBtn : ImageView
        ~ logger : Logger
        ~ microphoneActiveImage : Image
        ~ microphoneImageView : ImageView
        ~ microphoneInactiveImage : Image
        ~ settingBtn : ImageView
        ~ statusComboBox : ComboBox
        ~ statusList : ListView
        ~ topPane : BorderPane
        - imageBtn : Button
        - onlineCountLabel : Label
        - recordBtn : Button
        - userImageView : ImageView
        - userList : ListView
        - usernameLabel : Label
        - xOffset : double
        - yOffset : double
        + addAsServer()
        + addToChat()
        + closeApplication()
        + generateAnimation()
        + initialize()
        + logoutScene()
        + newUserNotification()
        + recordVoiceMessage()
        + sendButtonAction()
        + sendMethod()
        + setImageLabel()
        + setOnlineLabel()
        + setUserList()
        + setUsernameLabel()
    }
  }
  

  namespace com.client.chatwindow {
    class com.client.chatwindow.Listener {
        {static} + channel : String
        {static} + community : User
        + hostname : String
        + port : int
        {static} + username : String
        ~ logger : Logger
        {static} - COMMUNITY : String
        {static} - COMMUNITY_IMAGE : String
        {static} - HASCONNECTED : String
        - input : ObjectInputStream
        - is : InputStream
        {static} - oos : ObjectOutputStream
        - outputStream : OutputStream
        {static} - picture : String
        - socket : Socket
        + Listener()
        {static} + connect()
        + run()
        {static} + send()
        {static} + sendChannelUpadte()
        {static} + sendPicture()
        {static} + sendStatusUpdate()
        {static} + sendVoiceMessage()
    }
  }
  

  com.client.chatwindow.CellRenderer .up.|> javafx.util.Callback
  com.client.chatwindow.ChatController .up.|> javafx.fxml.Initializable
  com.client.chatwindow.Listener .up.|> java.lang.Runnable
  com.client.chatwindow.Listener o-- com.client.chatwindow.ChatController : controller


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
