@startuml

title __ANIMATIONS's Class Diagram__\n

  namespace com.traynotifications.animations {
    class com.traynotifications.animations.AnimationProvider {
        - animationsList : List<TrayAnimation>
        + AnimationProvider()
        + addAll()
        + findFirstWhere()
        + get()
        + where()
    }
  }
  

  namespace com.traynotifications.animations {
    enum AnimationType {
      FADE
      POPUP
      SLIDE
    }
  }
  

  namespace com.traynotifications.animations {
    class com.traynotifications.animations.FadeAnimation {
        - dismissAnimation : Timeline
        - showAnimation : Timeline
        - sq : SequentialTransition
        - trayIsShowing : boolean
        + FadeAnimation()
        + getAnimationType()
        + isShowing()
        + playDismissAnimation()
        + playSequential()
        + playShowAnimation()
        - setupDismissAnimation()
        - setupShowAnimation()
    }
  }
  

  namespace com.traynotifications.animations {
    class com.traynotifications.animations.PopupAnimation {
        - dismissAnimation : Timeline
        - showAnimation : Timeline
        - sq : SequentialTransition
        - trayIsShowing : boolean
        + PopupAnimation()
        + getAnimationType()
        + isShowing()
        + playDismissAnimation()
        + playSequential()
        + playShowAnimation()
        - setupDismissAnimation()
        - setupShowAnimation()
    }
  }
  

  namespace com.traynotifications.animations {
    class com.traynotifications.animations.SlideAnimation {
        - dismissAnimation : Timeline
        - showAnimation : Timeline
        - sq : SequentialTransition
        - trayIsShowing : boolean
        + SlideAnimation()
        + getAnimationType()
        + isShowing()
        + playDismissAnimation()
        + playSequential()
        + playShowAnimation()
        - setupDismissAnimation()
        - setupShowAnimation()
    }
  }
  

  namespace com.traynotifications.animations {
    interface com.traynotifications.animations.TrayAnimation {
        {abstract} + getAnimationType()
        {abstract} + isShowing()
        {abstract} + playDismissAnimation()
        {abstract} + playSequential()
        {abstract} + playShowAnimation()
    }
  }
  

  com.traynotifications.animations.FadeAnimation .up.|> com.traynotifications.animations.TrayAnimation
  com.traynotifications.animations.FadeAnimation o-- com.traynotifications.models.CustomStage : stage
  com.traynotifications.animations.PopupAnimation .up.|> com.traynotifications.animations.TrayAnimation
  com.traynotifications.animations.PopupAnimation o-- com.traynotifications.models.CustomStage : stage
  com.traynotifications.animations.SlideAnimation .up.|> com.traynotifications.animations.TrayAnimation
  com.traynotifications.animations.SlideAnimation o-- com.traynotifications.models.CustomStage : stage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
