@startuml

title __NOTIFICATION's Class Diagram__\n

  namespace com.traynotifications.notification {
    enum NotificationType {
      CUSTOM
      ERROR
      INFORMATION
      NOTICE
      SUCCESS
      WARNING
    }
  }
  

  namespace com.traynotifications.notification {
    class com.traynotifications.notification.TrayNotification {
        - imageIcon : ImageView
        - lblClose : Label
        - lblMessage : Label
        - lblTitle : Label
        - onDismissedCallBack : EventHandler<ActionEvent>
        - onShownCallback : EventHandler<ActionEvent>
        - rectangleColor : Rectangle
        - rootNode : AnchorPane
        + TrayNotification()
        + TrayNotification()
        + TrayNotification()
        + dismiss()
        + getAnimationType()
        + getImage()
        + getMessage()
        + getNotificationType()
        + getRectangleFill()
        + getTitle()
        + getTrayIcon()
        + isTrayShowing()
        + setAnimationType()
        + setImage()
        + setMessage()
        + setNotificationType()
        + setOnDismiss()
        + setOnShown()
        + setRectangleFill()
        + setTitle()
        + setTray()
        + setTray()
        + setTrayIcon()
        + showAndDismiss()
        + showAndWait()
        - initAnimations()
        - initStage()
        - initTrayNotification()
        - onDismissed()
        - onShown()
    }
  }
  

  com.traynotifications.notification.TrayNotification o-- com.traynotifications.animations.AnimationProvider : animationProvider
  com.traynotifications.notification.TrayNotification o-- com.traynotifications.animations.AnimationType : animationType
  com.traynotifications.notification.TrayNotification o-- com.traynotifications.animations.TrayAnimation : animator
  com.traynotifications.notification.TrayNotification o-- com.traynotifications.notification.NotificationType : notificationType
  com.traynotifications.notification.TrayNotification o-- com.traynotifications.models.CustomStage : stage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
